In [2]:
import torch 
from torch import nn
from d2l import torch as d2l
import math

In [3]:
n_train = 50
x_train , _ = torch.sort(torch.rand(n_train)*5)
def f(x):
    return 2 * torch.sin(x) + x**0.08
y_train = f(x_train) + torch.normal(0.0,0.5,(n_train,))

x_text = torch.arange(0,5,0.1)
y_truth = f(x_text)
n_text = len(x_text)
n_text

50

In [4]:
x_train   

tensor([0.1011, 0.2021, 0.2440, 0.3176, 0.8057, 0.8464, 0.9315, 1.0088, 1.0586,
        1.2494, 1.2525, 1.2934, 1.3840, 1.4242, 1.5122, 1.7960, 1.9917, 2.1398,
        2.3371, 2.3879, 2.4610, 2.4885, 2.5294, 2.6403, 2.9246, 3.0918, 3.1017,
        3.2163, 3.2181, 3.2366, 3.2450, 3.3108, 3.3286, 3.4607, 3.4879, 3.6308,
        3.6368, 3.7653, 3.9243, 3.9380, 3.9472, 4.0092, 4.1277, 4.2613, 4.3757,
        4.3778, 4.3876, 4.4639, 4.7356, 4.7756])

In [5]:
x_text

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
        4.5000, 4.6000, 4.7000, 4.8000, 4.9000])

In [6]:
X_repeat = x_text.repeat_interleave(n_train).reshape((-1,n_train))
attention_weights = nn.functional.softmax(-(X_repeat-x_train)**2/2)
y_hat = torch.matmul(attention_weights,y_train)

/tmp/ipykernel_6125/2577876924.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  attention_weights = nn.functional.softmax(-(X_repeat-x_train)**2/2)


In [11]:
def masked_softmax(X,valid_lens):
    if valid_lens is None:
        return nn.functional.softmax(X,dim=-1)
    else:
        shape =X.shape
        if valid_lens.dim() == 1:
            valid_lens = torch.repeat_interleave(valid_lens,shape[1])
        else:
            valid_lens = valid_lens.reshape(-1)
        X = d2l.sequence_mask(
            X.reshape(-1,shape[-1]),valid_len=valid_lens,
            value=-1e6
        )
    return nn.functional.softmax(X.reshape(shape),dim=-1)

In [12]:
masked_softmax(torch.rand(2,2,4),torch.tensor([2,3]))

tensor([[[0.4334, 0.5666, 0.0000, 0.0000],
         [0.6136, 0.3864, 0.0000, 0.0000]],

        [[0.5189, 0.2165, 0.2646, 0.0000],
         [0.3238, 0.4047, 0.2715, 0.0000]]])