In [2]:
import torch
from torch import nn

def conv2d(X,kernal):
    h , w =kernal.shape
    y = torch.zeros((X.shape[0] - h +1 , X.shape[1] - w + 1))
    for i in range(y.shape[0]):
        for x in range(y.shape[1]):
            y[i,x] = (X[i:i+h,x:x+w] * kernal).sum()

    return y



In [3]:
X = torch.tensor([[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]])
kernel = torch.tensor([[0.0,1.0],[2.0,3.0]])
y = conv2d(X,kernel)
y

tensor([[19., 25.],
        [37., 43.]])

In [4]:
class conv2d_(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))
    def forward(self,X):
        return conv2d(X,self.weight) + self.bias
cc = conv2d_((2,2))
y = cc(X)
y

tensor([[2.3528, 3.5999],
        [6.0939, 7.3409]], grad_fn=<AddBackward0>)

In [5]:
X = torch.ones((6,8))
X[:,2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [6]:
k = torch.tensor([[1,-1]])
y_hat = conv2d(X,k)
y_hat

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [7]:
_conv2d = nn.Conv2d(1,1,kernel_size=(1,2),bias=False)
X = X.reshape((1,1,6,8))
y = y_hat.reshape((1,1,6,7))
for i in range(10):
    y_hat = _conv2d(X)
    l = (y-y_hat)**2
    _conv2d.zero_grad()
    l.sum().backward()
    _conv2d.weight.data -= 3e-2 * _conv2d.weight.grad
    print(l.sum())

_conv2d.weight.data

tensor(16.5644, grad_fn=<SumBackward0>)
tensor(8.7054, grad_fn=<SumBackward0>)
tensor(4.7949, grad_fn=<SumBackward0>)
tensor(2.7507, grad_fn=<SumBackward0>)
tensor(1.6302, grad_fn=<SumBackward0>)
tensor(0.9899, grad_fn=<SumBackward0>)
tensor(0.6117, grad_fn=<SumBackward0>)
tensor(0.3825, grad_fn=<SumBackward0>)
tensor(0.2412, grad_fn=<SumBackward0>)
tensor(0.1528, grad_fn=<SumBackward0>)


tensor([[[[ 0.9504, -1.0305]]]])

In [14]:
m = torch.tensor([[1,1,1],[2,2,2]])
d =torch.stack((m,m+1,m+2),0)
d

tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[2, 2, 2],
         [3, 3, 3]],

        [[3, 3, 3],
         [4, 4, 4]]])