In [2]:
import torch
from torch import nn

In [3]:
def trans_conv(X,K):
    h,w = K.shape
    Y = torch.zeros((X.shape[0] + h -1,X.shape[1] + w -1)) 

    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            Y[i:i + h , j:j + w] += X[i,j] * K
    
    return Y

In [4]:
X = torch.tensor([[0.0,1.0],[2.0,3.0]])
K = torch.tensor([[0.0,1.0],[2.0,3.0]])

trans_conv(X,K)


tensor([[ 0.,  0.,  1.],
        [ 0.,  4.,  6.],
        [ 4., 12.,  9.]])

In [5]:
X,K = X.reshape(1,1,2,2),K.reshape(1,1,2,2)
tconv = nn.ConvTranspose2d(1,1,kernel_size=2,bias=False)
tconv.weight.data = K
tconv(X)

tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<ConvolutionBackward0>)

In [6]:
tconv = nn.ConvTranspose2d(1,1,kernel_size=2,padding=1,bias=False)
tconv.weight.data = K
tconv(X)

tensor([[[[4.]]]], grad_fn=<ConvolutionBackward0>)

In [7]:
tconv = nn.ConvTranspose2d(1,1,kernel_size=2,stride=2,bias=False)
tconv.weight.data = K
tconv(X)

tensor([[[[0., 0., 0., 1.],
          [0., 0., 2., 3.],
          [0., 2., 0., 3.],
          [4., 6., 6., 9.]]]], grad_fn=<ConvolutionBackward0>)

In [8]:
X = torch.arange(9.0).reshape(3,3)

K = K = torch.tensor([[1.0,2.0],[3.0,4.0]])


In [11]:
def kernel2matrix(K):
    k,w = torch.zeros(5),torch.zeros((4,9))
    k[:2],k[3:5] = K[0,:],K[1,:]
    w[0,:5], w[1,1:6],w[2,3:8],w[3,4:] = k,k,k,k
    return w

W = kernel2matrix(K)
W

tensor([[1., 2., 0., 3., 4., 0., 0., 0., 0.],
        [0., 1., 2., 0., 3., 4., 0., 0., 0.],
        [0., 0., 0., 1., 2., 0., 3., 4., 0.],
        [0., 0., 0., 0., 1., 2., 0., 3., 4.]])