In [2]:
import torch

In [3]:
def drop_out(p,X):
    mask = (torch.randn(X.shape) > p).float()
    return mask * X /(1-p)

x = torch.ones((3,2))
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
y = drop_out(0.1,x)
y

tensor([[1.1111, 0.0000],
        [1.1111, 1.1111],
        [1.1111, 0.0000]])

In [3]:
a1 = torch.tensor([1,1,1])
a2 = torch.tensor([2,2,2])
b = torch.cat([a1,a2])
b

tensor([1, 1, 1, 2, 2, 2])