In [2]:
import torch
from torch import nn

net = nn.Sequential(
    nn.Linear(20,256),
    nn.ReLU(),
    nn.Linear(256,10)
)

X = torch.rand(2,20)
net(X)

tensor([[-0.1563, -0.0939, -0.0995,  0.0680, -0.1852, -0.1102, -0.1033,  0.0302,
          0.0159,  0.1139],
        [-0.0949,  0.0053, -0.1337,  0.0597, -0.3144, -0.2417, -0.0579,  0.1460,
          0.0222, -0.1633]], grad_fn=<AddmmBackward0>)

In [3]:
class MLP(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.hidden = nn.Linear(20,256)
        self.out = nn.Linear(256,10)
    def forward(self,x):
        return self.out(
            nn.functional.relu(
                self.hidden(x)
                )
                )
    
    

In [4]:
mlp = MLP()
mlp(X)  

tensor([[ 0.1311, -0.1025, -0.0023,  0.4449,  0.0850, -0.0167, -0.0277, -0.1157,
         -0.0028, -0.1713],
        [ 0.2097, -0.1820,  0.0678,  0.5252,  0.3014,  0.2820, -0.1557, -0.0309,
          0.1626, -0.0636]], grad_fn=<AddmmBackward0>)

In [5]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for block in args:
            self._modules[block] = block
            #_modules存储每一个层次
    def forward(self,x):
        for block in self._modules:
            x = self._modules[block](x)
        return x

In [6]:
mySequential = MySequential(nn.Linear(20,256),nn.ReLU(),nn.Linear(256,20))
mySequential(X)

tensor([[-0.0314,  0.0086,  0.1921,  0.1685, -0.0268, -0.0832,  0.1739,  0.0237,
          0.1123,  0.1330, -0.2368, -0.3567, -0.0277, -0.3713,  0.0514,  0.0868,
          0.0530,  0.1382,  0.1842, -0.0025],
        [-0.0207,  0.0738,  0.2415,  0.2903,  0.0483, -0.0629, -0.0120, -0.0575,
          0.0378,  0.2715, -0.2435, -0.3688, -0.0015, -0.3860,  0.1626,  0.1011,
         -0.0522, -0.0285, -0.0169,  0.0098]], grad_fn=<AddmmBackward0>)

In [7]:
class FixedHidenMLP(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.rand_weight = torch.rand((20,20),requires_grad=False)
        print(self.rand_weight)
        self.linear = nn.Linear(20,20)

    def forward(self,x):
        x = self.linear(x)
        x = nn.functional.relu(torch.mm(x,self.rand_weight) + 1)
        x = self.linear(x)
        while x.abs().sum()>1:
            x/=2
        return x.sum()

net = FixedHidenMLP()
net(X)

tensor([[0.1176, 0.5253, 0.0810, 0.6533, 0.8439, 0.7275, 0.2293, 0.0317, 0.3611,
         0.4429, 0.2449, 0.7859, 0.0780, 0.5571, 0.2351, 0.9392, 0.9817, 0.5971,
         0.1370, 0.2063],
        [0.7332, 0.8218, 0.9665, 0.6742, 0.5876, 0.3272, 0.4257, 0.9351, 0.9907,
         0.2455, 0.6517, 0.8425, 0.1028, 0.1235, 0.4460, 0.7451, 0.6818, 0.7310,
         0.9973, 0.0883],
        [0.5233, 0.7091, 0.5605, 0.1077, 0.4590, 0.0365, 0.1171, 0.9115, 0.8605,
         0.5638, 0.5301, 0.3768, 0.3272, 0.1396, 0.3287, 0.4059, 0.0131, 0.2461,
         0.0068, 0.5053],
        [0.9554, 0.1717, 0.0141, 0.7964, 0.9954, 0.2760, 0.0114, 0.2313, 0.4736,
         0.2756, 0.7745, 0.5717, 0.9940, 0.0161, 0.8987, 0.1239, 0.3773, 0.2726,
         0.7920, 0.8808],
        [0.5553, 0.1954, 0.8601, 0.5409, 0.0624, 0.5248, 0.9617, 0.3059, 0.5369,
         0.1424, 0.4110, 0.6561, 0.8370, 0.5233, 0.6737, 0.9737, 0.6507, 0.5511,
         0.2186, 0.3120],
        [0.1941, 0.0492, 0.4209, 0.7148, 0.1700, 0.3408, 0.1

tensor(-0.2711, grad_fn=<SumBackward0>)

In [8]:
import torch 
from torch import nn
net = nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
x = torch.rand((2,4))
net(x)

tensor([[-0.1892],
        [-0.4348]], grad_fn=<AddmmBackward0>)

In [9]:
print(net.state_dict())

OrderedDict({'0.weight': tensor([[-0.0144,  0.3360,  0.0708,  0.4889],
        [-0.2393, -0.2710,  0.4229, -0.1168],
        [ 0.1400, -0.0177,  0.3402, -0.0009],
        [-0.3558, -0.1241,  0.1511, -0.1392],
        [-0.2038,  0.2363,  0.1366,  0.3959],
        [ 0.0528,  0.2139, -0.1727,  0.0112],
        [ 0.1685, -0.1272, -0.2787, -0.4560],
        [-0.0203,  0.4009,  0.1082, -0.4037]]), '0.bias': tensor([ 0.4968, -0.0687,  0.3989, -0.3411, -0.3010,  0.3217,  0.1634,  0.1873]), '2.weight': tensor([[-0.2831, -0.1837, -0.2420,  0.0758, -0.2390,  0.0609,  0.2733, -0.0329]]), '2.bias': tensor([0.1917])})


In [13]:
name , param = net[0].named_parameters()
type(net[0].weight.data)

torch.Tensor

In [11]:
x.device

device(type='cpu')