In [113]:
import torch 
import torchvision
from torch.utils import data
from torchvision import transforms


In [ ]:

trans = transforms.Compose(
    [
        transforms.ToTensor()
    ]
)
mninst_train = torchvision.datasets.FashionMNIST(
    root='FashionMINIST',
    train=True,
    download=True,
    transform=trans
    )
mninst_text = torchvision.datasets. FashionMNIST(
    root="FashionMINIST",
    train=False,
    download=True,
    transform=trans
)


len(mninst_train),len(mninst_text)

(60000, 10000)

In [115]:
mninst_train[0][0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0510,
          0.2863, 0.0000, 0.0000, 0.0039, 0.0157, 0.0000,

In [116]:
from torch.utils.tensorboard import SummaryWriter

# writer = SummaryWriter('log')
# for index,data_ in enumerate(mninst_train):
#     writer.add_image('Minist',data_[0],index)

In [117]:
import matplotlib.pyplot as plt

In [118]:
train_dataloader = data.DataLoader(
    dataset=mninst_train,
    batch_size=256,
    shuffle=True,
    num_workers=4,
    drop_last=True
)
# writer = SummaryWriter('dataloader')

# for index,data_ in enumerate(train_dataloader):

#     writer.add_images('da',data_[0],index)

text_dataloader = data.DataLoader(
    dataset = mninst_text,
    batch_size=256,
    num_workers=4,
    drop_last=True
)

In [119]:
from IPython import display
num_inputs = 28*28 
num_out = 10
w = torch.normal(0,0.01,size=(num_inputs,num_out),requires_grad=True)
b = torch.zeros(num_out,requires_grad=True)

def softmax(X):
    exp_x = torch.exp(X)
    p = exp_x.sum(1,keepdim=True)
    return exp_x / p

X = torch.normal(0,1,(2,5))

x_prad = softmax(X)
x_prad , x_prad.sum(1)

(tensor([[0.0991, 0.5271, 0.1867, 0.1375, 0.0495],
         [0.0396, 0.3836, 0.0796, 0.0404, 0.4569]]),
 tensor([1., 1.]))

In [120]:
def net(w,b,X):
    return softmax(torch.matmul(X.reshape((256,-1)),w) + b )
def lossfunction(y_hat , y):

    return -torch.log(y_hat[range(y_hat.shape[0]),y])

y = torch.tensor([0,2])
y_hat = torch.tensor([[0.1,0.3,0.6],
                      [0.3,0.2,0.5]])
loss = lossfunction(y_hat,y)
loss

tensor([2.3026, 0.6931])

In [121]:
def accuracy(y_hat,y):
    predictIndex = y_hat.argmax(axis=1)
    result = (predictIndex == y).sum()
    return result / y_hat.shape[0]
accur = accuracy(y_hat,y)
accur

tensor(0.5000)

In [122]:
def sgd(params,lr):
    with torch.no_grad():
        for param in params:
            param -= lr* param.grad/256
            
            param.grad.zero_()

 

In [123]:
for _  in range(3):
    for X,y in train_dataloader:
        y_hat = net(w,b,X)
        loss = lossfunction(y_hat,y)
        L2 = (0 * w**2).sum()
        (loss.sum() + L2).backward()
        sgd([w,b],lr=0.01)
        ac= accuracy(y_hat,y)
    print(ac)
    print(loss.sum()/256 + L2)
with torch.no_grad():
    for X,y in text_dataloader:
        y_hat= net(w,b,X)
        ac = accuracy(y_hat,y)
        print(ac)


tensor(0.6953)
tensor(1.0013, grad_fn=<AddBackward0>)
tensor(0.7500)
tensor(0.8746, grad_fn=<AddBackward0>)
tensor(0.7695)
tensor(0.7629, grad_fn=<AddBackward0>)
tensor(0.7695)
tensor(0.7852)
tensor(0.7500)
tensor(0.7578)
tensor(0.7188)
tensor(0.7695)
tensor(0.7891)
tensor(0.7578)
tensor(0.7969)
tensor(0.7734)
tensor(0.7656)
tensor(0.7227)
tensor(0.6797)
tensor(0.7305)
tensor(0.7266)
tensor(0.6875)
tensor(0.7461)
tensor(0.8594)
tensor(0.7695)
tensor(0.7266)
tensor(0.7734)
tensor(0.7070)
tensor(0.7227)
tensor(0.7617)
tensor(0.7500)
tensor(0.7500)
tensor(0.7266)
tensor(0.7422)
tensor(0.7500)
tensor(0.7695)
tensor(0.7344)
tensor(0.7070)
tensor(0.7422)
tensor(0.7773)
tensor(0.7266)
tensor(0.7188)
tensor(0.7344)
tensor(0.7656)
tensor(0.7578)


In [124]:
from torch.nn import(
    Sequential,
    Flatten,
    CrossEntropyLoss,
    Linear
)
from torch.optim import SGD
net = Sequential(
    Flatten(),
    Linear(784,10)
)
loss_ = CrossEntropyLoss()
optimer = SGD(net.parameters(),lr=0.01)
for _ in range(10):
    for X , y in train_dataloader:
        y_hat = net(X)
        acc = accuracy(y_hat,y)
        loss = loss_(y_hat , y)
        optimer.zero_grad()
        loss.backward()
        optimer.step()
    print(loss)
    print(acc)


tensor(1.0526, grad_fn=<NllLossBackward0>)
tensor(0.6758)
tensor(0.9033, grad_fn=<NllLossBackward0>)
tensor(0.7344)
tensor(0.8265, grad_fn=<NllLossBackward0>)
tensor(0.7578)
tensor(0.8100, grad_fn=<NllLossBackward0>)
tensor(0.7148)
tensor(0.6858, grad_fn=<NllLossBackward0>)
tensor(0.7734)
tensor(0.6657, grad_fn=<NllLossBackward0>)
tensor(0.7930)
tensor(0.5135, grad_fn=<NllLossBackward0>)
tensor(0.8750)
tensor(0.6041, grad_fn=<NllLossBackward0>)
tensor(0.7812)
tensor(0.6136, grad_fn=<NllLossBackward0>)
tensor(0.7969)
tensor(0.6258, grad_fn=<NllLossBackward0>)
tensor(0.7812)
